
services:
  postgres:
    image: postgres:latest
    container_name: leaderboard_postgres
    restart: always
    environment:
      POSTGRES_USER: leaderboard
      POSTGRES_PASSWORD: leaderboard
      POSTGRES_DB: leaderboard
    ports:
      - "5432:5432"
    volumes:
      - leaderboard_postgres_data:/var/lib/postgresql/data

volumes:
  leaderboard_postgres_data:
    external: true

networks:
  default:
    name: ingress
    external: true
